### ISSUE TITLE
can you share pre trained weights?

### ISSUE THREAD

**Issue by manvirvirk** [hcleung35/SRGAN_Cramer#1]

**Comment by hcleung35** [comment]
The pre-trained weights are in the models file.
U can directly download my package to run the evaluation code.

May I know where do u find my repo since I cannot google my repo and I am struggle with it?
If u find my project is meaningful, may u give me a star?
Thank you very much.

**Comment by manvirvirk** [comment]
I already marked star, i found pre trained weights but i m getting following error when testing my image , please check. Thanks
  File "myeval.py", line 18, in myevaluate
    valid_lr_img = valid_lr_imgs[imidx]
IndexError: list index out of range

**Comment by hcleung35** [comment]
Thank you for that.
I have 1 image in img folder.
U can directly use the following cmd to run the code.
python myeval.py --mode myevaluate 0

**Comment by manvirvirk** [comment]
Still is is showing same error

**Comment by hcleung35** [comment]
Sorry my bad, u need to place your image in myval folder.

**Comment by manvirvirk** [comment]
still it is showing this error, i m using image if tiff format and
resolution 565*584
(srgan) D:\SRGAN_Cramer-master>python myeval.py --mode myevaluate 1
2020-06-13 20:57:18.197299: I
tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully
opened dynamic library cudart64_101.dll
Traceback (most recent call last):
  File "myeval.py", line 54, in <module>
    myevaluate(args.imidx)
  File "myeval.py", line 18, in myevaluate
    valid_lr_img = valid_lr_imgs[imidx]
IndexError: list index out of range

**Comment by hcleung35** [comment]
I see. As the program only accept png format, tiff may cause the problem.

**Comment by manvirvirk** [comment]
I checked with png also still same error

**Comment by hcleung35** [comment]
May I know what files include in the myval folder?

**Comment by manvirvirk** [comment]
its random rgb image of resolution 565*584 with name 0.png

**Comment by hcleung35** [comment]
Have u try my original 0.png?
Is it ok?

**Comment by manvirvirk** [comment]
let me try and revert back

**Comment by manvirvirk** [comment]
got super resolved image. thanks (y)

**Comment by manvirvirk** [comment]
Hi, i had gone through the code, it is similar as SRGAN . I m having query
in which of part Cramer loss has been incorporated?
Thanks

**Comment by hcleung35** [comment]
My adversarial learning for generator and discriminator is totally different from the SRGAN.
For instance, the original SRGAN compute the generator and discriminator loss by the cross entropy.  With the Cramer framework, I compute the surrogate generator loss and critical discriminator loss instead (see train_cam.py).
Also, we don't need the pre-train stage because of the Cramer, which can save certain amount of training time.
Hope that, this info can answer your query.

**Comment by manvirvirk** [comment]
Thanks, i got the point. I thing more i want to ask is the basic
architecture for discriminator and generator is same as SRGAN or there is
difference?

**Comment by hcleung35** [comment]
There is difference in the discriminator, i.e. the output is the energy loss vector instead of logit.
The generator is more a less the same.

**Comment by manvirvirk** [comment]
Thanks for the help. (y)
